name: Windows RDP
on: workflow_dispatch
jobs:
  rdp:
    runs-on: windows-latest
    timeout-minutes: 300
    steps:
    - name: Enable RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd123!" -Force)
        
    - name: Install and Setup Ngrok
      env:
        NGROK_AUTH: ${{ secrets.NGROK_AUTHTOKEN }}
      run: |
        choco install ngrok -y
        ngrok authtoken $env:NGROK_AUTH
        
    - name: Start RDP Tunnel
      run: |
        Start-Process -FilePath "ngrok" -ArgumentList "tcp 3389" -NoNewWindow
        Start-Sleep -Seconds 10
        $tunnels = Invoke-RestMethod http://127.0.0.1:4040/api/tunnels
        $address = $tunnels.tunnels[0].public_url
        Write-Output "================================"
        Write-Output "RDP Address: $address"
        Write-Output "Username: runneradmin"
        Write-Output "Password: P@ssw0rd123!"
        Write-Output "================================"
        
    - name: Keep Alive
      run: Start-Sleep -Seconds 18000
